Refactor all moderation features, auto mod and notes. Add reports and modlog.
r-Techsupport/TechSupportBot pull request #1095
Opened 2024-07-22 13:07 UTC by ajax146

This is a complete rewrite and restructure of protect and everything related to it.

protect.py was split into:
commands/moderator.py
commands/purge.py
core/moderation.py
functions/automod.py
functions/paste.py

Two additional files were added:
commands/modlog.py
commands/report.py

who.py was split into:
commands/notes.py
commands/whois.py

commands/moderator.py:
Moved all moderator actions into slash commands
Adds a new /unwarn command allowing individual warnings to be removed
Logs and displays who warned people (Fixes #657)
Mute can now have both a duration and a reason (fixes #721)

commands/modlog.py
Completely new feature, copying carlbots /modlog highscores and ban/unban logging
This additionally adds the ability to lookup bans by user or moderator
Bans are now forever stored in TS database (Fixes #380)

commands/notes.py
All the notes editing commands, as well as a /notes all
Write roles checks now check reader roles as well (fixes #692)
Makes notes all paginated (fixes #800)
Notes reader/writer now only send one message if config is empty (fixes #983)

commands/purge.py
Moves purge command to /purge
Combines the duration and exact command

commands/whois.py
Is the /whois command

core/moderation.py
This handles the core actions of ban/unban/kick/mute/unmute/warn/unwarn and a few core logic items, like getting all warnings

functions/automod.py
Completely rewrites automod (Fixes #463)
Fixes regex not working (no issue for this one)
Adds a mute feature for automod (Fixes #1020)
Adds automod as a framework instead of a strict class, allowing other modules to run messages through automod
Adds IRC checks to automod (Fixes #212)

functions/paste.py
Paste now makes sure that the linx API request worked and that the message was sent BEFORE deleting the original message (Fixes #1077)
Paste checks if message violates automod, and if it was recommended that it was deleted, nothing happens

Other:
Who now shows new warning information (Fixes #180)
Moves duck to use the new core/moderation.py feature

2024-07-30 23:53 UTC, TheKrol commented
Here is the list so far of things to I have found wrong:
1) Warning by the bot, make sure it is displayed by the bot
2) Report will fail if user has not avatar url
3) Modmail highscore will fail if user left the server on list.
4) Add the limit of purge to the error message
5) Purge log has a target which is not needed
6) Automod can warn people who are above them in role rank

2024-07-31 05:46 UTC, TheKrol requested changes
More things to fix:
1) Edge case, too many warning/notes will over load whois and warnings all
2) Don't know if it is possible, but make report mention the user if you link a message of theirs?
3) IRC automod worked for only Delete = True silent and warn = false, but it printed nothing in the chat, only in logs. Therefore, none of the other messages worked because nothing is printed in the main chat from IRC only logs

2025-04-28 23:11 UTC, TheKrol commented
Better ban reason when going over 7 days
![image](https://github.com/user-attachments/assets/9ffed0fe-e7f5-4909-b4dc-bbdb52674c46)

2025-04-28 23:12 UTC, TheKrol commented
Limit ban/unban reason length to 1024
![image](https://github.com/user-attachments/assets/38804337-8c43-4175-a0e6-325d72bb415f)

2025-04-28 23:37 UTC, TheKrol commented
![image](https://github.com/user-attachments/assets/f0ef6f65-b15f-422f-9e78-42bdda237cd8)
Should the errors be the same, either not let you do the command, or tell you what is wrong
![image](https://github.com/user-attachments/assets/7b8b2f8a-cb4b-4cb5-84fd-4dbc949761b5)

2025-04-28 23:39 UTC, TheKrol commented
Log warn and purge in a channel.

2025-04-28 23:57 UTC, TheKrol commented
![image](https://github.com/user-attachments/assets/6f64220b-8803-4e9f-80ad-25d8c38bebe7)
Add a how long they were muted for here?

2025-04-29 00:12 UTC, TheKrol commented
In report if you use <@1149691126161346670> It will error out with unknown User
![image](https://github.com/user-attachments/assets/62cc84e2-8206-47fc-bccb-7ee6005ed45b)

2025-04-29 00:34 UTC, TheKrol commented
Make delete in automod not delete the message the bot will post

2025-04-29 01:20 UTC, TheKrol approved these changes

2025-04-29 18:15 UTC, dkay0670 commented on techsupport_bot/commands/purge.py
> +            return
There are maximum limits of 2 weeks and 100 messages for purge, maybe add checks for that

2025-04-29 18:41 UTC, dkay0670 commented on techsupport_bot/commands/moderator.py
> +        async for ban in interaction.guild.bans(limit=None):
[Guild.fetch_ban(user)](https://discordpy.readthedocs.io/en/stable/api.html#discord.Guild.fetch_ban) seems like it could work. raises NotFound when the user isnt banned.

2025-04-29 21:12 UTC, dkay0670 reviewed
Mostly just string changes

2025-04-29 21:20 UTC, TheKrol commented on techsupport_bot/commands/whois.py
> +                flags.append("Is a guest")
![image](https://github.com/user-attachments/assets/404db791-c2f1-4268-8bd0-bd5af893ba9e)
So if a member hasn't done the rules yet

2025-05-03 22:12 UTC, TheKrol commented
It appears your int for delete days broke 
![image](https://github.com/user-attachments/assets/2282d1a4-60dd-4a78-a978-91fe32fc2f90)

2025-05-03 22:14 UTC, TheKrol commented
If you want to change this here, make unwarn show how many warnings they still have?

2025-05-04 03:54 UTC, dkay0670 commented
Fixes #800

2025-05-05 17:59 UTC, merged