Implement IRC directly into the bot
r-Techsupport/TechSupportBot pull request #521
Opened 2023-07-16 22:31 UTC by ajax146

This completely replaces relay with a custom IRC bot, using the irc python package
RabbitMQ is no longer needed and has been removed
IRC links are now stored in postgres, and the config.yml file will have to be modified

This is a near feature-to-feature conversion with a few new features:
A .irc ban/unban command, to ban/unban people on IRC
A .irc disconnect/reconnect command, to deal with the IRC connection

Application no longer works with IRC, though the original was incomplete anyway

IRC status has been added to .bot, and .bot is now inline

Fixes #60 
Fixes #397 
Fixes #447 

These two issues will no longer be relevant
Closes #57 
Closes #505

2023-07-17 13:24 UTC, Cpt-Dingus requested changes
This will fix all codefactor issues for relay.py

2023-07-17 13:24 UTC, Cpt-Dingus commented on techsupport_bot/extensions/relay.py
> +            message=f"Are you sure you want to unlink <#{ctx.channel.id}> and {self.mapping[str(ctx.channel.id)]}",
```suggestion
            message=f"Are you sure you want to unlink <#{ctx.channel.id}>"
            + f"and {self.mapping[str(ctx.channel.id)]}",
```

2023-07-17 13:24 UTC, Cpt-Dingus commented on techsupport_bot/extensions/relay.py
> +                message=f"The link between <#{ctx.channel.id}> and {self.mapping[str(ctx.channel.id)]} was not deleted",
```suggestion
                message=f"The link between <#{ctx.channel.id}> and"
                + f"{self.mapping[str(ctx.channel.id)]} was not deleted",
```

2023-07-20 17:35 UTC, TheKrol approved these changes

2023-07-20 20:53 UTC, Cpt-Dingus approved these changes

2023-07-20 20:58 UTC, merged