Add Context Menu command for Whois
r-Techsupport/TechSupportBot pull request #868
Opened 2024-02-13 01:33 UTC by dkay0670

Add Context Menu command for Whois

2024-02-14 00:00 UTC, SaintTheAce approved these changes

2024-04-01 18:57 UTC, TheKrol requested changes
Doesn't work with no reader set.

2024-07-05 22:35 UTC, dkay0670 commented
I still don't understand why the test is failing

On Friday, July 05, 2024 11:00 PDT, ajax146 ***@***.***> wrote:
 
 
@dkay0670 @TheKrol What is the status on this?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/r-Techsupport/TechSupportBot/pull/868#issuecomment-2211228373", "url": "https://github.com/r-Techsupport/TechSupportBot/pull/868#issuecomment-2211228373", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]***>

 

2024-07-05 22:38 UTC, dkay0670 commented
nvm wrong pr, I just need to fix it, I'll set myself a reminder

2025-04-30 18:45 UTC, dkay0670 commented
closing since this whole file will be gone after #1095 gets merged. will try and implement this with the new code

2025-04-30 18:45 UTC, closed without merging